begin;

create extension if not exists unaccent;
create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.players (
  player_id bigint generated by default as identity primary key,
  nba_player_id integer not null unique,
  full_name text not null,
  first_name text,
  last_name text,
  team text,
  team_abbreviation text,
  position text,
  birthdate date,
  height_in integer,
  weight_lbs numeric(6,2),
  country text,
  draft_year text,
  draft_round text,
  draft_number text,
  from_year integer,
  to_year integer,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.traditional_stats (
  stat_id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(player_id) on delete cascade,
  season text not null check (season ~ '^[0-9]{4}-[0-9]{2}$'),
  gp integer,
  gs integer,
  min_per_game numeric(8,3),
  pts_per_game numeric(8,3),
  reb_per_game numeric(8,3),
  ast_per_game numeric(8,3),
  stl_per_game numeric(8,3),
  blk_per_game numeric(8,3),
  tov_per_game numeric(8,3),
  fg_pct numeric(8,4),
  fg3_pct numeric(8,4),
  ft_pct numeric(8,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint traditional_stats_player_season_unique unique (player_id, season)
);

create table if not exists public.advanced_stats (
  stat_id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(player_id) on delete cascade,
  season text not null check (season ~ '^[0-9]{4}-[0-9]{2}$'),
  gp integer,
  min_per_game numeric(8,3),
  off_rating numeric(8,3),
  def_rating numeric(8,3),
  net_rating numeric(8,3),
  ts_pct numeric(8,4),
  usg_pct numeric(8,4),
  efg_pct numeric(8,4),
  pie numeric(8,4),
  pace numeric(8,3),
  ast_pct numeric(8,4),
  reb_pct numeric(8,4),
  oreb_pct numeric(8,4),
  dreb_pct numeric(8,4),
  tm_tov_pct numeric(8,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint advanced_stats_player_season_unique unique (player_id, season)
);

create index if not exists idx_players_full_name_trgm
  on public.players using gin (full_name gin_trgm_ops);

create index if not exists idx_players_full_name_lower
  on public.players (lower(full_name));

create index if not exists idx_traditional_stats_player_season
  on public.traditional_stats (player_id, season);

create index if not exists idx_advanced_stats_player_season
  on public.advanced_stats (player_id, season);

create index if not exists idx_traditional_stats_season
  on public.traditional_stats (season);

create index if not exists idx_advanced_stats_season
  on public.advanced_stats (season);

drop trigger if exists set_players_updated_at on public.players;
create trigger set_players_updated_at
before update on public.players
for each row execute function public.set_updated_at();

drop trigger if exists set_traditional_stats_updated_at on public.traditional_stats;
create trigger set_traditional_stats_updated_at
before update on public.traditional_stats
for each row execute function public.set_updated_at();

drop trigger if exists set_advanced_stats_updated_at on public.advanced_stats;
create trigger set_advanced_stats_updated_at
before update on public.advanced_stats
for each row execute function public.set_updated_at();

create or replace view public.player_season_stats as
select
  coalesce(t.player_id, a.player_id) as player_id,
  p.nba_player_id,
  p.full_name,
  coalesce(t.season, a.season) as season,
  p.team,
  p.position,
  t.gp as traditional_gp,
  t.min_per_game as traditional_min_per_game,
  t.pts_per_game,
  t.reb_per_game,
  t.ast_per_game,
  t.stl_per_game,
  t.blk_per_game,
  t.tov_per_game,
  t.fg_pct,
  t.fg3_pct,
  t.ft_pct,
  a.gp as advanced_gp,
  a.min_per_game as advanced_min_per_game,
  a.off_rating,
  a.def_rating,
  a.net_rating,
  a.ts_pct,
  a.usg_pct,
  a.efg_pct,
  a.pie,
  a.pace,
  a.ast_pct,
  a.reb_pct,
  a.oreb_pct,
  a.dreb_pct,
  a.tm_tov_pct
from public.traditional_stats t
full outer join public.advanced_stats a
  on t.player_id = a.player_id
 and t.season = a.season
join public.players p
  on p.player_id = coalesce(t.player_id, a.player_id);

create or replace view public.current_season_stats as
select
  a.stat_id,
  a.player_id,
  a.season,
  a.off_rating,
  a.def_rating,
  a.ts_pct,
  a.usg_pct,
  a.efg_pct,
  a.pie,
  t.pts_per_game as pts,
  t.reb_per_game as reb,
  t.ast_per_game as ast
from public.advanced_stats a
left join public.traditional_stats t
  on t.player_id = a.player_id
 and t.season = a.season;

commit;
